// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * 获取支持的漏洞列表
 */
export class PocInfo {
    /**
     * Creates a new PocInfo instance.
     * @param {Partial<PocInfo>} [$$source = {}] - The source object to create the PocInfo.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PocInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PocInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PocInfo(/** @type {Partial<PocInfo>} */($$parsedSource));
    }
}
