// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * 基本信息说明
 * @returns {$CancellablePromise<string>}
 */
export function GetInfo() {
    return $Call.ByID(907839606);
}

/**
 * @returns {$CancellablePromise<$models.PocInfo[]>}
 */
export function GetPocList() {
    return $Call.ByID(715229540).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * 查询漏洞是否已确认存在
 * @param {string} pocType
 * @returns {$CancellablePromise<boolean>}
 */
export function IsVulnerable(pocType) {
    return $Call.ByID(465079682, pocType);
}

/**
 * 控制器主入口：漏洞检测与利用
 * @param {string} url
 * @param {string} pocType
 * @param {string} action
 * @param {string} payload
 * @param {string} filename
 * @param {string} expType
 * @returns {$CancellablePromise<string>}
 */
export function POC(url, pocType, action, payload, filename, expType) {
    return $Call.ByID(1988867184, url, pocType, action, payload, filename, expType);
}

/**
 * 设置漏洞是否存在状态
 * @param {string} pocType
 * @param {boolean} vulnerable
 * @returns {$CancellablePromise<void>}
 */
export function SetVulnerable(pocType, vulnerable) {
    return $Call.ByID(1958283782, pocType, vulnerable);
}

// Private type creation functions
const $$createType0 = $models.PocInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
