// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是一个包装器，用于将 config 包的方法暴露给 Wails
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetGlobalHeaders 调用 config 包的函数
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetGlobalHeaders() {
    return $Call.ByID(4152951363).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetProxy 调用 config 包的函数
 * @returns {$CancellablePromise<string>}
 */
export function GetProxy() {
    return $Call.ByID(4044764172);
}

/**
 * SetGlobalHeaders 调用 config 包的函数
 * @param {{ [_: string]: string }} headers
 * @returns {$CancellablePromise<void>}
 */
export function SetGlobalHeaders(headers) {
    return $Call.ByID(4037868951, headers);
}

/**
 * SetProxy 调用 config 包的函数
 * @param {string} proxy
 * @returns {$CancellablePromise<void>}
 */
export function SetProxy(proxy) {
    return $Call.ByID(2072968832, proxy);
}

/**
 * TestProxy 调用 config 包的函数
 * @param {string} proxy
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function TestProxy(proxy) {
    return $Call.ByID(740070484, proxy);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
